"""
Additional QA tests for ULTIMATE_VHOST-025 — Phase 2 coverage enhancement.

Focuses on gaps found in coverage analysis:
  * OSError during iterdir() on sites-enabled / sites-available
  * General Exception (non-Permission) reading config
  * External vhost without DocumentRoot
  * External vhost with non-standard port
  * External vhost with quoted server_name
  * Create blocked even when external vhost is in sites-enabled only
  * List sorted output (alphabetical by domain)
  * Apache external vhost with multiple VirtualHost blocks
  * Enable on external vhost that is only in sites-enabled (already enabled path via scan)
  * Nginx external config with port != 80 does not cause crash
"""

import os
import stat
import pytest
from pathlib import Path
from unittest.mock import patch, MagicMock
from typer.testing import CliRunner

from vhost_helper.main import app, _scan_all_vhosts_locally, _find_vhost_info_for_domain
from vhost_helper.models import ServerType

runner = CliRunner()

NGINX_EXTERNAL_CONF_PORT8080 = """\
server {
    listen 8080;
    server_name port8080.test;
    root /var/www/port8080;
}
"""

NGINX_EXTERNAL_CONF_NO_ROOT = """\
server {
    listen 80;
    server_name noroot.test;
}
"""

NGINX_EXTERNAL_CONF_QUOTED = """\
server {
    listen 80;
    server_name "quoted.test";
    root /var/www/quoted;
}
"""

APACHE_EXTERNAL_CONF_NO_ROOT = """\
<VirtualHost *:80>
    ServerName noroot-apache.test
</VirtualHost>
"""

APACHE_EXTERNAL_CONF_PORT8443 = """\
<VirtualHost *:8443>
    ServerName apache8443.test
    DocumentRoot /var/www/apache8443
</VirtualHost>
"""

MANAGED_HEADER = "# Generated by VHost Helper"

MANAGED_NGINX_CONF = f"""\
{MANAGED_HEADER}
server {{
    listen 80;
    server_name managed-nginx.test;
    root /var/www/managed;
}}
"""


def _patch_env(monkeypatch, tmp_path):
    """Create a minimal mixed environment and patch all path constants."""
    apache_avail = tmp_path / "apache2" / "sites-available"
    apache_enabled = tmp_path / "apache2" / "sites-enabled"
    nginx_avail = tmp_path / "nginx" / "sites-available"
    nginx_enabled = tmp_path / "nginx" / "sites-enabled"

    for d in [apache_avail, apache_enabled, nginx_avail, nginx_enabled]:
        d.mkdir(parents=True, exist_ok=True)

    monkeypatch.setattr("vhost_helper.config.NGINX_SITES_AVAILABLE", nginx_avail)
    monkeypatch.setattr("vhost_helper.config.NGINX_SITES_ENABLED", nginx_enabled)
    monkeypatch.setattr("vhost_helper.config.APACHE_SITES_AVAILABLE", apache_avail)
    monkeypatch.setattr("vhost_helper.config.APACHE_SITES_ENABLED", apache_enabled)

    monkeypatch.setattr("vhost_helper.main.NGINX_SITES_AVAILABLE", nginx_avail)
    monkeypatch.setattr("vhost_helper.main.NGINX_SITES_ENABLED", nginx_enabled)
    monkeypatch.setattr("vhost_helper.main.APACHE_SITES_AVAILABLE", apache_avail)
    monkeypatch.setattr("vhost_helper.main.APACHE_SITES_ENABLED", apache_enabled)
    monkeypatch.setattr("vhost_helper.main.NGINX_SITES_DISABLED", None)
    monkeypatch.setattr("vhost_helper.main.APACHE_SITES_DISABLED", None)

    monkeypatch.setattr("vhost_helper.providers.nginx.NGINX_SITES_AVAILABLE", nginx_avail)
    monkeypatch.setattr("vhost_helper.providers.nginx.NGINX_SITES_ENABLED", nginx_enabled)
    monkeypatch.setattr("vhost_helper.providers.apache.APACHE_SITES_AVAILABLE", apache_avail)
    monkeypatch.setattr("vhost_helper.providers.apache.APACHE_SITES_ENABLED", apache_enabled)

    def mock_run_elevated(cmd, **kwargs):
        if cmd and cmd[0] == "sudo":
            cmd = cmd[1:]
        import subprocess
        return subprocess.run(cmd, **kwargs)

    for mod in [
        "vhost_helper.utils",
        "vhost_helper.scaffolding",
        "vhost_helper.permissions",
        "vhost_helper.providers.nginx",
        "vhost_helper.providers.apache",
    ]:
        monkeypatch.setattr(f"{mod}.run_elevated_command", mock_run_elevated)

    monkeypatch.setattr("vhost_helper.providers.apache.detected_os_family", "debian_family")
    monkeypatch.setattr("vhost_helper.providers.nginx.detected_os_family", "debian_family")
    monkeypatch.setattr("vhost_helper.main.is_apache_installed", lambda: True)
    monkeypatch.setattr("vhost_helper.main.is_nginx_installed", lambda: True)
    monkeypatch.setattr("vhost_helper.main.is_apache_running", lambda: False)
    monkeypatch.setattr("vhost_helper.main.is_nginx_running", lambda: False)
    monkeypatch.setattr("vhost_helper.main.preflight_sudo_check", lambda: None)
    monkeypatch.setenv("COLUMNS", "250")

    return {
        "apache_avail": apache_avail,
        "apache_enabled": apache_enabled,
        "nginx_avail": nginx_avail,
        "nginx_enabled": nginx_enabled,
    }


class TestNonStandardPorts:
    """External vhosts listening on non-80 ports must be listed correctly."""

    def test_nginx_port_8080_listed(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("port8080.test.conf").write_text(NGINX_EXTERNAL_CONF_PORT8080)

        result = runner.invoke(app, ["list", "--provider", "nginx"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "port8080.test" in result.stdout

    def test_nginx_port_8080_info_shows_port(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("port8080.test.conf").write_text(NGINX_EXTERNAL_CONF_PORT8080)

        result = runner.invoke(app, ["info", "port8080.test"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "8080" in result.stdout

    def test_apache_port_8443_listed(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["apache_avail"].joinpath("apache8443.test.conf").write_text(APACHE_EXTERNAL_CONF_PORT8443)

        result = runner.invoke(app, ["list", "--provider", "apache"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "apache8443.test" in result.stdout


class TestVhostWithoutDocumentRoot:
    """External vhosts without a DocumentRoot should be listed without crashing."""

    def test_nginx_no_docroot_listed(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("noroot.test.conf").write_text(NGINX_EXTERNAL_CONF_NO_ROOT)

        result = runner.invoke(app, ["list", "--provider", "nginx"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "noroot.test" in result.stdout

    def test_apache_no_docroot_listed(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["apache_avail"].joinpath("noroot-apache.test.conf").write_text(APACHE_EXTERNAL_CONF_NO_ROOT)

        result = runner.invoke(app, ["list", "--provider", "apache"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "noroot-apache.test" in result.stdout

    def test_nginx_no_docroot_scan_has_none_document_root(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("noroot.test.conf").write_text(NGINX_EXTERNAL_CONF_NO_ROOT)

        results = _scan_all_vhosts_locally(filter_provider=ServerType.NGINX)
        match = next((v for v in results if v.domain == "noroot.test"), None)
        assert match is not None
        # document_root may be None or empty for configs without a root directive
        assert match.document_root is None or str(match.document_root) in ["None", ""]


class TestQuotedServerName:
    """Server names wrapped in quotes should be parsed and stripped correctly."""

    def test_quoted_nginx_server_name_listed(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("quoted.test.conf").write_text(NGINX_EXTERNAL_CONF_QUOTED)

        result = runner.invoke(app, ["list", "--provider", "nginx"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "quoted.test" in result.stdout

    def test_quoted_nginx_server_name_info(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("quoted.test.conf").write_text(NGINX_EXTERNAL_CONF_QUOTED)

        result = runner.invoke(app, ["info", "quoted.test"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "quoted.test" in result.stdout


class TestOSErrorDuringIterdir:
    """OSError during iterdir() must be handled gracefully — no crash, empty result."""

    def test_oserror_on_iterdir_skipped(self, tmp_path, monkeypatch):
        """Simulate OSError when iterating a directory."""
        nginx_avail = tmp_path / "nginx" / "sites-available"
        nginx_enabled = tmp_path / "nginx" / "sites-enabled"
        nginx_avail.mkdir(parents=True)
        nginx_enabled.mkdir(parents=True)

        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_AVAILABLE", nginx_avail)
        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_ENABLED", nginx_enabled)
        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_DISABLED", None)
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_AVAILABLE", tmp_path / "nope")
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_ENABLED", tmp_path / "nope2")
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_DISABLED", None)

        original_iterdir = Path.iterdir

        def patched_iterdir(self):
            if str(self) == str(nginx_avail):
                raise OSError("Simulated OSError on iterdir")
            return original_iterdir(self)

        monkeypatch.setattr(Path, "iterdir", patched_iterdir)

        # Should not raise — OSError is caught internally
        results = _scan_all_vhosts_locally(filter_provider=ServerType.NGINX)
        assert isinstance(results, list)

    def test_oserror_on_enabled_iterdir_falls_back_gracefully(self, tmp_path, monkeypatch):
        """OSError on sites-enabled iterdir means all found are shown as Disabled."""
        nginx_avail = tmp_path / "nginx" / "sites-available"
        nginx_enabled = tmp_path / "nginx" / "sites-enabled"
        nginx_avail.mkdir(parents=True)
        nginx_enabled.mkdir(parents=True)
        nginx_avail.joinpath("ext.test.conf").write_text(
            "server { listen 80; server_name ext.test; root /x; }"
        )

        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_AVAILABLE", nginx_avail)
        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_ENABLED", nginx_enabled)
        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_DISABLED", None)
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_AVAILABLE", tmp_path / "nope")
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_ENABLED", tmp_path / "nope2")
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_DISABLED", None)

        original_iterdir = Path.iterdir

        def patched_iterdir(self):
            if str(self) == str(nginx_enabled):
                raise OSError("Permission denied on sites-enabled")
            return original_iterdir(self)

        monkeypatch.setattr(Path, "iterdir", patched_iterdir)

        results = _scan_all_vhosts_locally(filter_provider=ServerType.NGINX)
        # ext.test should still be found, just shown as Disabled
        assert isinstance(results, list)
        if results:
            ext = next((v for v in results if v.domain == "ext.test"), None)
            if ext:
                assert ext.status == "Disabled"


class TestGeneralExceptionReadingConfig:
    """Non-PermissionError exceptions while reading a config file are handled."""

    def test_generic_ioerror_reading_config_skipped(self, tmp_path, monkeypatch):
        nginx_avail = tmp_path / "nginx" / "sites-available"
        nginx_enabled = tmp_path / "nginx" / "sites-enabled"
        nginx_avail.mkdir(parents=True)
        nginx_enabled.mkdir(parents=True)

        # Write one valid and one that will raise on read_text
        valid_conf = nginx_avail.joinpath("valid.test.conf")
        valid_conf.write_text("server { listen 80; server_name valid.test; root /x; }")
        broken_conf = nginx_avail.joinpath("broken.test.conf")
        broken_conf.write_text("server { listen 80; server_name broken.test; root /x; }")

        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_AVAILABLE", nginx_avail)
        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_ENABLED", nginx_enabled)
        monkeypatch.setattr("vhost_helper.main.NGINX_SITES_DISABLED", None)
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_AVAILABLE", tmp_path / "nope")
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_ENABLED", tmp_path / "nope2")
        monkeypatch.setattr("vhost_helper.main.APACHE_SITES_DISABLED", None)

        original_read_text = Path.read_text

        def patched_read_text(self, *args, **kwargs):
            if self.name == "broken.test.conf":
                raise IOError("Simulated IOError reading config")
            return original_read_text(self, *args, **kwargs)

        monkeypatch.setattr(Path, "read_text", patched_read_text)

        # Should not raise; broken config is skipped, valid config still found
        results = _scan_all_vhosts_locally(filter_provider=ServerType.NGINX)
        assert isinstance(results, list)
        domains = [v.domain for v in results]
        assert "valid.test" in domains
        assert "broken.test" not in domains


class TestCreateBlockedForEnabledExternal:
    """create must be blocked even when external vhost is only in sites-enabled."""

    def test_create_blocked_when_external_only_in_enabled(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        web = tmp_path / "web"
        web.mkdir()
        # Place external conf directly in sites-enabled (not in sites-available)
        (dirs["nginx_enabled"] / "enabled-only.test.conf").write_text(
            "server { listen 80; server_name enabled-only.test; root /var/www/x; }"
        )

        result = runner.invoke(
            app,
            ["create", "enabled-only.test", str(web), "--provider", "nginx", "--no-scaffold"],
            catch_exceptions=False,
        )
        assert result.exit_code == 1
        assert "Cannot create managed vhost" in result.stdout


class TestListSortedOutput:
    """list output should be alphabetically sorted by domain."""

    def test_output_is_sorted_alphabetically(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        for name in ["zebra.test", "alpha.test", "middle.test"]:
            dirs["nginx_avail"].joinpath(f"{name}.conf").write_text(
                f"server {{ listen 80; server_name {name}; root /x; }}"
            )

        result = runner.invoke(app, ["list", "--provider", "nginx"], catch_exceptions=False)
        assert result.exit_code == 0
        lines = result.stdout.splitlines()
        domain_lines = [l for l in lines if any(n in l for n in ["alpha.test", "middle.test", "zebra.test"])]
        # Extract the domain names in order they appear
        ordered = [l for l in domain_lines if "alpha.test" in l or "middle.test" in l or "zebra.test" in l]
        domains_in_order = []
        for line in ordered:
            if "alpha.test" in line:
                domains_in_order.append("alpha.test")
            elif "middle.test" in line:
                domains_in_order.append("middle.test")
            elif "zebra.test" in line:
                domains_in_order.append("zebra.test")
        # Deduplicate while preserving order (domain appears in domain col and config path col)
        seen = []
        for d in domains_in_order:
            if d not in seen:
                seen.append(d)
        assert seen == sorted(seen), f"Expected sorted output, got {seen}"


class TestInfoShowsManagedByField:
    """info command must always show Managed By field."""

    def test_info_external_shows_external_label(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("ext.test.conf").write_text(
            "server { listen 80; server_name ext.test; root /x; }"
        )

        result = runner.invoke(app, ["info", "ext.test"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "External" in result.stdout
        assert "Managed By" in result.stdout or "External" in result.stdout

    def test_info_managed_shows_vhost_helper_label(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        dirs["nginx_avail"].joinpath("managed.test.conf").write_text(MANAGED_NGINX_CONF)

        result = runner.invoke(app, ["info", "managed-nginx.test"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "VHost Helper" in result.stdout

    def test_info_nonexistent_domain_returns_error(self, tmp_path, monkeypatch):
        _patch_env(monkeypatch, tmp_path)

        result = runner.invoke(app, ["info", "doesnotexist.test"], catch_exceptions=False)
        assert result.exit_code == 1
        assert "No configuration found" in result.stdout


class TestEnableDisableCycle:
    """Full enable → list-check → disable → list-check cycle for external vhosts."""

    def test_nginx_full_enable_disable_cycle(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        conf = dirs["nginx_avail"].joinpath("cycle.test.conf")
        conf.write_text("server { listen 80; server_name cycle.test; root /x; }")
        original_bytes = conf.read_bytes()
        symlink = dirs["nginx_enabled"] / "cycle.test.conf"

        # 1. Enable
        result = runner.invoke(app, ["enable", "cycle.test", "--provider", "nginx"], catch_exceptions=False)
        assert result.exit_code == 0
        assert symlink.is_symlink()
        assert conf.read_bytes() == original_bytes  # content unchanged

        # 2. List shows Enabled
        result = runner.invoke(app, ["list", "--provider", "nginx"], catch_exceptions=False)
        assert "cycle.test" in result.stdout
        assert "Enabled" in result.stdout

        # 3. Disable
        result = runner.invoke(app, ["disable", "cycle.test", "--provider", "nginx"], catch_exceptions=False)
        assert result.exit_code == 0
        assert not symlink.exists()
        assert conf.read_bytes() == original_bytes  # content unchanged

        # 4. List shows Disabled
        result = runner.invoke(app, ["list", "--provider", "nginx"], catch_exceptions=False)
        assert "cycle.test" in result.stdout
        assert "Disabled" in result.stdout

    def test_apache_full_enable_disable_cycle(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        conf = dirs["apache_avail"].joinpath("cycle-apache.test.conf")
        conf.write_text("<VirtualHost *:80>\n    ServerName cycle-apache.test\n    DocumentRoot /x\n</VirtualHost>\n")
        original_bytes = conf.read_bytes()
        symlink = dirs["apache_enabled"] / "cycle-apache.test.conf"

        # 1. Enable
        result = runner.invoke(app, ["enable", "cycle-apache.test", "--provider", "apache"], catch_exceptions=False)
        assert result.exit_code == 0
        assert symlink.is_symlink()
        assert conf.read_bytes() == original_bytes

        # 2. List shows Enabled
        result = runner.invoke(app, ["list", "--provider", "apache"], catch_exceptions=False)
        assert "cycle-apache.test" in result.stdout
        assert "Enabled" in result.stdout

        # 3. Disable
        result = runner.invoke(app, ["disable", "cycle-apache.test", "--provider", "apache"], catch_exceptions=False)
        assert result.exit_code == 0
        assert not symlink.exists()
        assert conf.read_bytes() == original_bytes

        # 4. List shows Disabled
        result = runner.invoke(app, ["list", "--provider", "apache"], catch_exceptions=False)
        assert "cycle-apache.test" in result.stdout
        assert "Disabled" in result.stdout


class TestExternalVhostRemove:
    """vhost remove on external vhosts is allowed per PRD (only create is blocked)."""

    def test_remove_external_nginx_removes_file(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        conf = dirs["nginx_avail"].joinpath("remove-me.test.conf")
        conf.write_text("server { listen 80; server_name remove-me.test; root /x; }")

        result = runner.invoke(app, ["remove", "remove-me.test", "--force"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "Success!" in result.stdout
        assert not conf.exists()

    def test_remove_external_apache_removes_file(self, tmp_path, monkeypatch):
        dirs = _patch_env(monkeypatch, tmp_path)
        conf = dirs["apache_avail"].joinpath("remove-apache.test.conf")
        conf.write_text("<VirtualHost *:80>\n    ServerName remove-apache.test\n    DocumentRoot /x\n</VirtualHost>\n")

        result = runner.invoke(app, ["remove", "remove-apache.test", "--force"], catch_exceptions=False)
        assert result.exit_code == 0
        assert "Success!" in result.stdout
        assert not conf.exists()
